### PR TITLE
Enhanced the CSS Styling of webpage

### PR DESCRIPTION
**Pull request by shrutimishra27**
Solves issue #42 

Corrected all these problems:

- [x] Edit and Delete Button touching the border of component
- [x] Edit and Delete Button are not showing up as buttons on hovering
- [x] Date Box is clashing with pink border

## Edited:
Screenshot 2023-10-20 213753

## Original
Screenshot 2023-10-20 152358

### CODE REVIEW

**Comment by Pranavnk15** [comment]
Thank you for your invaluable contributions to our open-source project! 🚀 If you like our project, please consider to start ⭐ the repo.

**Comment by shrutimishra27** [comment]
@Pranavnk15  this issue is not showing up on my hacktoberfest profile.
Please add hacktoberfest-accepted label.

**Comment by shrutimishra27** [comment]
> Thank you for your invaluable contributions to our open-source project! 🚀 If you like our project, please consider to start ⭐ the repo.

Sure starred ⭐

**Comment by Pranavnk15** [comment]
Don't worry the hacktober fest site, refreshes every 15mins, it'll show up,

**Comment by shrutimishra27** [comment]
> Don't worry the hacktober fest site, refreshes every 15mins, it'll show up,

Thanks a lot for your cooperation @Pranavnk15

**Comment by Pranavnk15** [comment]
> > Don't worry the hacktober fest site, refreshes every 15mins, it'll show up,
> 
> Thanks a lot for your cooperation @Pranavnk15 

Any time...

**Pull request merged**
