### PR TITLE
Setup esLint to check for errors and syntax. Added a CI workflow for the same.

### LINKED ISSUE #16: Add github workflows
Try adding a GitHub workflow for auto commenting, on raising a issue, 
or
performing test on pull request

### PR DESCRIPTION
**Pull request by Rachit1313**
Fixes #16 .

Kindly let me know if any changes are required.

### CODE REVIEW

**Comment by Pranavnk15** [comment]
there seems to be some conflicts in package-lock.json file

**Comment by Rachit1313** [comment]
just fixed the conflict.

**Comment by Pranavnk15** [comment]
so can you explain me what will it function like?

**Comment by Rachit1313** [comment]
Can you open this PR too?

**Comment by Pranavnk15** [comment]
nope... you need to again sync the repo clone and then make changes, and then again make a new PR

**Comment by Pranavnk15** [comment]
can't open it again once merged

**Comment by Rachit1313** [comment]
Not a problem. I’ll make the new PR. Sorry for inconvenience.

**Comment by Pranavnk15** [comment]
Nope, not an issue, I am too learning new things by maintaining  the project

**Pull request merged**
